# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

resources:
  webhooks:
    - webhook: IssueUpdateWebHook
      connection: TestWebHookConnect

pool:
  vmImage: ubuntu-latest

parameters:
  - name: IssueUpdateWebHook
    type: object
    default: {}

variables:
    Question: ${{ parameters.IssueUpdateWebHook.resource.revision.fields['System.Description'] }}
    WorkItemID: ${{ parameters.IssueUpdateWebHook.resource.workItemId }}

steps:
- script: |
    echo Pipeline Start.
    echo ---------------------
    echo "$(Question)"
    echo "$(WorkItemID)"
    echo ---------------------
    echo Pipeline End
  displayName: 'Run a multi-line script'


